# Generated by Django 2.2.5 on 2020-05-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pbio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pbio',
            new_name='bio',
        ),
    ]
